artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: snap/amazon-fine-food-reviews
  local_data_file: artifacts/data_ingestion/amazon-fine-food-reviews/
  unzip_dir: artifacts/data_ingestion
