artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: snap/amazon-fine-food-reviews
  local_data_file: artifacts/data_ingestion/amazon-fine-food-reviews/
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  # base_model_path: artifacts/prepare_base_model/logistic_regression_model.pkl
  # updated_base_model_path: artifacts/prepare_base_model/updated_logistic_regression_model.pkl
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  # trained_model_path: artifacts/training/model.h5
  trained_model_path: artifacts/training/logistic_regression_model.pkl
  trained_stop_words_path: artifacts/training/english_stop_words.pkl
  trained_vectorizer_path: artifacts/training/vectorizer.pkl
  trained_stemmer_path: artifacts/training/stemmer.pkl

evaluation:
  dataset_path: artifacts/data_ingestion/Reviews.csv
  ml_flow_tracking_url: "https://dagshub.com/Abhisekh97/Sentiment-Analysis.mlflow"
  